# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: trusty
sudo: true

cache:
  packages: true

before_install:
  - sudo apt-get -y install libnlopt-dev

r_binary_packages: 
 - rstan
 - rstanarm
 - stringi
 - StanHeaders
 - Rcpp
 - RcppEigen


r:
- oldrel
- release
- devel

after_success:
  - Rscript -e 'covr::codecov()'

# circa 2018-06-21, oldrel takes 45m+ to build and causes timeout error

matrix:
  allow_failures:
    - r: oldrel

